### PR TITLE
chore: bump semver dep

### PR DESCRIPTION
**Pull request by yusinto**
Updating semver to latest. The reason it was pinned to 7.5.0 was because 7.5.0 introduced require('util') without the node: prefix. This has been fixed in [7.5.1](https://github.com/npm/node-semver/releases/tag/v7.5.1) so we'll update to latest which is 7.5.4.

### CODE REVIEW

**Comment by kinyoklion** [comment]
What confidence level do we have that this will execute nicely in cloudflare, vercel, akamai? Are the current unit tests sufficiently representative of those environments?

@dariushar @ctawiah @monsagri

**Review by louis-launchdarkly — DISMISSED** [review]

**Review by kinyoklion — CHANGES_REQUESTED** [review]
Requesting changes until my question is addressed.

**Review by dariushar — APPROVED** [review]
Someone else may be a little more confident than I am but I took a quick look at the Akamai and Vervel SDKs and I don't see any issues being caused by this

**Comment by ctawiah** [comment]
> What confidence level do we have that this will execute nicely in cloudflare, vercel, akamai? Are the current unit tests sufficiently representative of those environments?
> 
> @dariushar @ctawiah @monsagri

LGTM

**Review by ctawiah — APPROVED** [review]

**Review by monsagri — APPROVED** [review]

**Comment by monsagri** [comment]
Looks good to me from what I can see!

**Review by kinyoklion — APPROVED** [review]

**Pull request merged**
