### PR TITLE
fix: bump cloudflare sdk dep

### PR DESCRIPTION
**Pull request by yusinto**
fix: bump cloudflare sdk dep

### CODE REVIEW

**Comment by kinyoklion** [comment]
This is a "fix" which will make another release, is that what you want?

**Comment by yusinto** [comment]
For now, a patch release is fine I think. Otherwise the example app fails due to the serialization bug, which is not very good for our customers. Is that ok with you please?

**Review by kinyoklion — APPROVED** [review]

**Comment by kinyoklion** [comment]
> For now, a patch release is fine I think. Otherwise the example app fails due to the serialization bug, which is not very good for our customers. Is that ok with you please?

I approved, but I wasn't sure if someone would be running an example from the package, or the repo. If it is just the repo, then you just need a "chore". But if you want it updated in the package, then this is the right thing to do.

**Comment by yusinto** [comment]
Good point re your last comment. Preferably both scenarios should work, so the caret added should somewhat solve this kind of patch releases to a certain extent. Agree we may need to re-structure the example location.

**Pull request merged**
